name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        app-name: ["apple", "banana"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Echo Start
        run: echo "Start"
      -
        name: Matrix
        uses: ./.github/actions/matrix
        with:
          app-name: ${{ matrix.app-name }}
