name: ci

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags and histories
      - name: Echo Start
        run: echo "Start"
      - name: Set tag if it is main branch
        uses: ./.github/actions/set-calendar-version-tag
        if: github.ref == 'refs/heads/main'
      - name: Login to artifactory server
        run: |
          docker login --username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_TOKEN }} ${{ secrets.ARTIFACTORY_PATH }}
      # - name: Fetch tag name
      #   id: fetch-tag-name
      #   run: |
      #     if [[ "${{ github.ref }}" = "refs/heads/main" ]]; then
      #       echo "result=20230928"
      #     else
      #       echo "result=${{ github.ref_name }}"
      #     fi >> $GITHUB_OUTPUT
      # - name: Run Build and Push
      #   run: bash ./scripts/build_and_push.sh ${{ steps.fetch-tag-name.outputs.result }}
      - name: Run Build and Push
        run: bash ./scripts/build_and_push.sh
