name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo Start
        run: echo "Start"
      - name: Run Build and Push
        run: sh ./scripts/build_and_push.sh
