name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo Start
        run: echo "Start"
      - name: Set tag if it is master branch
        uses: ./.github/actions/set-calendar-version-tag
        if: github.ref == 'refs/heads/master'
      - name: Fetch version
        shell: bash
        run: |
          echo "${{ github.ref }}"
          if [[ "${{ github.ref }}" = "refs/heads/master" ]];
            echo "20230928"
          else
            echo "${{ github.ref_name }}"
          fi
      - name: Run Build and Push
        run: bash ./scripts/build_and_push.sh
